# Generated by Django 5.0.14 on 2025-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Bank Transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='salary',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('On Hold', 'On Hold')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
