# Generated by Django 5.0.14 on 2025-06-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
