# Generated by Django 5.0.14 on 2025-06-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee'), ('User', 'User')], default='User', max_length=10),
        ),
    ]
