# Generated by Django 5.0.14 on 2025-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
