# Generated by Django 5.0.14 on 2025-06-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='name',
            new_name='leavetype',
        ),
    ]
