# Generated by Django 5.0.14 on 2025-06-18 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_request', '0002_rename_name_leavetype_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_request.leavetype'),
        ),
    ]
